tabs:
  main:
    display: Main
    sections:
      -
        display: Profile
        instructions: 'Owner Details'
        fields:
          -
            handle: owner
            field:
              type: text
              display: Owner
          -
            handle: city
            field:
              type: text
              display: City
          -
            handle: country
            field:
              type: text
              display: Country
